export const MLS_ATTRIBUTION = [
  "The data relating to real estate on this website comes in part from the",
  "MLS® Reciprocity program of either the Greater Vancouver REALTORS® (GVR),",
  "the Fraser Valley Real Estate Board (FVREB) or the Chilliwack and District",
  "Real Estate Board (CADREB). This representation is based in whole or part",
  "on data generated by either the GVR, the FVREB or the CADREB which assumes",
  "no responsibility for its accuracy. The materials contained on this page",
  "may not be reproduced without the express written consent of either the",
  "GVR, the FVREB or the CADREB.",
].join(" ");
